/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedMoodRouteImport } from './routes/_authenticated/mood'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedEntriesEntryIdRouteImport } from './routes/_authenticated/entries.$entryId'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals.index'
import { Route as AuthenticatedGoalsGoalIdRouteImport } from './routes/_authenticated/goals.$goalId'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people.$personId'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsWeekStartRouteImport } from './routes/_authenticated/reports.$weekStart'
import { Route as AuthenticatedTopicsIndexRouteImport } from './routes/_authenticated/topics.index'
import { Route as AuthenticatedTopicsTopicIdRouteImport } from './routes/_authenticated/topics.$topicId'
import { Route as AuthenticatedVoiceIndexRouteImport } from './routes/_authenticated/voice.index'
import { Route as AuthenticatedVoiceSessionIdRouteImport } from './routes/_authenticated/voice.$sessionId'
import { Route as AuthenticatedWriteSessionIdRouteImport } from './routes/_authenticated/write.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoodRoute = AuthenticatedMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntriesEntryIdRoute =
  AuthenticatedEntriesEntryIdRouteImport.update({
    id: '/entries/$entryId',
    path: '/entries/$entryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsGoalIdRoute =
  AuthenticatedGoalsGoalIdRouteImport.update({
    id: '/goals/$goalId',
    path: '/goals/$goalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsWeekStartRoute =
  AuthenticatedReportsWeekStartRouteImport.update({
    id: '/reports/$weekStart',
    path: '/reports/$weekStart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTopicsIndexRoute =
  AuthenticatedTopicsIndexRouteImport.update({
    id: '/topics/',
    path: '/topics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTopicsTopicIdRoute =
  AuthenticatedTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVoiceIndexRoute = AuthenticatedVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceSessionIdRoute =
  AuthenticatedVoiceSessionIdRouteImport.update({
    id: '/voice/$sessionId',
    path: '/voice/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWriteSessionIdRoute =
  AuthenticatedWriteSessionIdRouteImport.update({
    id: '/write/$sessionId',
    path: '/write/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AuthenticatedAskRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/mood': typeof AuthenticatedMoodRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/entries/$entryId': typeof AuthenticatedEntriesEntryIdRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/reports/$weekStart': typeof AuthenticatedReportsWeekStartRoute
  '/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/voice/$sessionId': typeof AuthenticatedVoiceSessionIdRoute
  '/write/$sessionId': typeof AuthenticatedWriteSessionIdRoute
  '/goals/': typeof AuthenticatedGoalsIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/topics/': typeof AuthenticatedTopicsIndexRoute
  '/voice/': typeof AuthenticatedVoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AuthenticatedAskRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/mood': typeof AuthenticatedMoodRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/entries/$entryId': typeof AuthenticatedEntriesEntryIdRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/reports/$weekStart': typeof AuthenticatedReportsWeekStartRoute
  '/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/voice/$sessionId': typeof AuthenticatedVoiceSessionIdRoute
  '/write/$sessionId': typeof AuthenticatedWriteSessionIdRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/topics': typeof AuthenticatedTopicsIndexRoute
  '/voice': typeof AuthenticatedVoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/mood': typeof AuthenticatedMoodRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/entries/$entryId': typeof AuthenticatedEntriesEntryIdRoute
  '/_authenticated/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/reports/$weekStart': typeof AuthenticatedReportsWeekStartRoute
  '/_authenticated/topics/$topicId': typeof AuthenticatedTopicsTopicIdRoute
  '/_authenticated/voice/$sessionId': typeof AuthenticatedVoiceSessionIdRoute
  '/_authenticated/write/$sessionId': typeof AuthenticatedWriteSessionIdRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/topics/': typeof AuthenticatedTopicsIndexRoute
  '/_authenticated/voice/': typeof AuthenticatedVoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ask'
    | '/history'
    | '/insights'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/entries/$entryId'
    | '/goals/$goalId'
    | '/people/$personId'
    | '/reports/$weekStart'
    | '/topics/$topicId'
    | '/voice/$sessionId'
    | '/write/$sessionId'
    | '/goals/'
    | '/people/'
    | '/reports/'
    | '/topics/'
    | '/voice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ask'
    | '/history'
    | '/insights'
    | '/journal'
    | '/mood'
    | '/onboarding'
    | '/entries/$entryId'
    | '/goals/$goalId'
    | '/people/$personId'
    | '/reports/$weekStart'
    | '/topics/$topicId'
    | '/voice/$sessionId'
    | '/write/$sessionId'
    | '/goals'
    | '/people'
    | '/reports'
    | '/topics'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ask'
    | '/_authenticated/history'
    | '/_authenticated/insights'
    | '/_authenticated/journal'
    | '/_authenticated/mood'
    | '/_authenticated/onboarding'
    | '/_authenticated/entries/$entryId'
    | '/_authenticated/goals/$goalId'
    | '/_authenticated/people/$personId'
    | '/_authenticated/reports/$weekStart'
    | '/_authenticated/topics/$topicId'
    | '/_authenticated/voice/$sessionId'
    | '/_authenticated/write/$sessionId'
    | '/_authenticated/goals/'
    | '/_authenticated/people/'
    | '/_authenticated/reports/'
    | '/_authenticated/topics/'
    | '/_authenticated/voice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mood': {
      id: '/_authenticated/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof AuthenticatedMoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entries/$entryId': {
      id: '/_authenticated/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof AuthenticatedEntriesEntryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/$goalId': {
      id: '/_authenticated/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$weekStart': {
      id: '/_authenticated/reports/$weekStart'
      path: '/reports/$weekStart'
      fullPath: '/reports/$weekStart'
      preLoaderRoute: typeof AuthenticatedReportsWeekStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/': {
      id: '/_authenticated/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof AuthenticatedTopicsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/$topicId': {
      id: '/_authenticated/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicsTopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice/': {
      id: '/_authenticated/voice/'
      path: '/voice'
      fullPath: '/voice/'
      preLoaderRoute: typeof AuthenticatedVoiceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice/$sessionId': {
      id: '/_authenticated/voice/$sessionId'
      path: '/voice/$sessionId'
      fullPath: '/voice/$sessionId'
      preLoaderRoute: typeof AuthenticatedVoiceSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/write/$sessionId': {
      id: '/_authenticated/write/$sessionId'
      path: '/write/$sessionId'
      fullPath: '/write/$sessionId'
      preLoaderRoute: typeof AuthenticatedWriteSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMoodRoute: typeof AuthenticatedMoodRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedEntriesEntryIdRoute: typeof AuthenticatedEntriesEntryIdRoute
  AuthenticatedGoalsGoalIdRoute: typeof AuthenticatedGoalsGoalIdRoute
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedReportsWeekStartRoute: typeof AuthenticatedReportsWeekStartRoute
  AuthenticatedTopicsTopicIdRoute: typeof AuthenticatedTopicsTopicIdRoute
  AuthenticatedVoiceSessionIdRoute: typeof AuthenticatedVoiceSessionIdRoute
  AuthenticatedWriteSessionIdRoute: typeof AuthenticatedWriteSessionIdRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedTopicsIndexRoute: typeof AuthenticatedTopicsIndexRoute
  AuthenticatedVoiceIndexRoute: typeof AuthenticatedVoiceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMoodRoute: AuthenticatedMoodRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedEntriesEntryIdRoute: AuthenticatedEntriesEntryIdRoute,
  AuthenticatedGoalsGoalIdRoute: AuthenticatedGoalsGoalIdRoute,
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedReportsWeekStartRoute: AuthenticatedReportsWeekStartRoute,
  AuthenticatedTopicsTopicIdRoute: AuthenticatedTopicsTopicIdRoute,
  AuthenticatedVoiceSessionIdRoute: AuthenticatedVoiceSessionIdRoute,
  AuthenticatedWriteSessionIdRoute: AuthenticatedWriteSessionIdRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedTopicsIndexRoute: AuthenticatedTopicsIndexRoute,
  AuthenticatedVoiceIndexRoute: AuthenticatedVoiceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
